### ISSUE TITLE
swagger ui returns 500 error

### ISSUE THREAD

**Issue by Machine-Maker** [PaperMC/library#2]
Testing the api using the swagger ui, specifically this request `curl -X GET "https://papermc.io/api/v2/projects/paper/versions/1.16.4/builds/256/downloads/test" -H  "accept: application/java-archive"` returns a 500 error in the "Try it out". But if i just run that curl command locally, I get 404 like it should (because `test` is not a valid download name)

**Comment by kashike** [comment]
Route returns mixed content types - drop the `-H "accept: application/java-archive"`.
