### ISSUE TITLE
"Latest" option is missing in API V2

### ISSUE THREAD

**Issue by DutchFlander** [PaperMC/library#3]
https://github.com/PaperMC/Paper/issues/4824#issuecomment-736125764

Hi,

reference:
https://paper.readthedocs.io/en/latest/site/api.html#i-just-want-to-download-the-latest-jar

In API V2 the "latest" build option is missing. It was present in V1:
https://papermc.io/api/v1/paper/1.16.4/latest/download
But it is not updated anymore.
Bug report:
https://github.com/PaperMC/Paper/issues/4824

**Comment by clrxbl** [comment]
By design to prevent auto updaters from existing.

**Comment by kashike** [comment]
The v1 `latest` endpoint is updated - it had a cache duration that was too long and has been fixed (https://github.com/PaperMC/library/commit/6b37a50c1a12f4b6d66005e5a2f58b14b775b68d).

v2 is not "missing" the `latest` endpoint, it was intentionally not done.
